# Generated by Django 2.1.2 on 2019-02-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabeleireiro',
            name='CELULAR',
            field=models.CharField(max_length=30, verbose_name='CELULAR'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CELULAR',
            field=models.CharField(max_length=30, verbose_name='CELULAR'),
        ),
    ]
