# Generated by Django 2.2 on 2019-06-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='url'),
        ),
    ]
