# Generated by Django 2.1.2 on 2019-05-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='cabeleleiros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabeleleiros', to='website.cabeleleiro'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='clientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='website.cliente'),
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='servicos',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servicos',
            field=models.ManyToManyField(related_name='servicos', to='website.servico'),
        ),
    ]
