# Generated by Django 2.2 on 2019-06-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.IntegerField(choices=[('09', '09:00'), ('093', '09:30'), ('10', '10:00'), ('103', '10:30'), ('11', '11:00'), ('113', '11:30'), ('12', '12:00'), ('123', '12:30'), ('13', '13:00'), ('133', '13:30'), ('14', '14:00'), ('143', '14:30'), ('15', '15:00'), ('153', '15:30'), ('16', '16:00'), ('163', '16:30'), ('17', '17:00'), ('173', '17:30'), ('18', '18:00')], verbose_name='hora_inicio'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='especificacao',
            field=models.CharField(max_length=400, verbose_name='Especificacao'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='validade_produto',
            field=models.DateField(verbose_name='Validade produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor unitario'),
        ),
    ]
