# Generated by Django 2.1.2 on 2019-03-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabeleleiro',
            name='EMAIL',
            field=models.EmailField(max_length=100, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='cabeleleiro',
            name='SENHA',
            field=models.CharField(max_length=200, verbose_name='SENHA'),
        ),
    ]
