# Generated by Django 2.2 on 2019-06-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190622_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='url'),
        ),
    ]
