# Generated by Django 2.1.2 on 2019-02-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190208_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CABELEIREIRO',
            new_name='CABELELEIRO',
        ),
    ]
