# Generated by Django 2.1.2 on 2019-02-09 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190208_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGENDAMENTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA', models.DateField(verbose_name='DATA')),
                ('HORA_INICIO', models.TimeField(verbose_name='HORA_INICIO')),
                ('HORA_FIM', models.TimeField(verbose_name='HORA_FIM')),
                ('CABELELEIROS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.CABELELEIRO')),
                ('CLIENTES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.CLIENTE')),
                ('SERVICOS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.SERVICO')),
            ],
        ),
    ]
