# Generated by Django 2.1.2 on 2019-02-16 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='DATA',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='HORA_FIM',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='HORA_INICIO',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='DATA_FIM',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATA_FIM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='DATA_INICIO',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATA_INICIO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='STATUS',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='STATUS'),
            preserve_default=False,
        ),
    ]
