# Generated by Django 2.2 on 2019-06-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190619_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.TimeField(verbose_name='hora_inicio'),
        ),
    ]
