# Generated by Django 2.2 on 2019-06-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190619_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='especificacao',
            field=models.CharField(max_length=400, verbose_name='especificacao'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='validade_produto',
            field=models.DateField(verbose_name='validade_produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valor_unitario'),
        ),
    ]
