# Generated by Django 2.2 on 2019-06-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190619_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='produtos',
            field=models.ManyToManyField(null=True, related_name='produtos', to='website.produto'),
        ),
    ]
