# Generated by Django 2.2 on 2019-06-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190621_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='produtos',
            field=models.ManyToManyField(related_name='produtos', to='website.produto'),
        ),
    ]
