# Generated by Django 2.2 on 2019-06-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190621_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='produtos',
            field=models.ManyToManyField(blank=True, null=True, related_name='produtos', to='website.produto'),
        ),
    ]
