# Generated by Django 2.1.2 on 2019-03-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='CABELELEIROS',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='CLIENTES',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='SERVICOS',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='ID_PRODUTO',
        ),
        migrations.DeleteModel(
            name='AGENDAMENTO',
        ),
        migrations.DeleteModel(
            name='CABELELEIRO',
        ),
        migrations.DeleteModel(
            name='CLIENTE',
        ),
        migrations.DeleteModel(
            name='ESTOQUE',
        ),
        migrations.DeleteModel(
            name='PRODUTO',
        ),
        migrations.DeleteModel(
            name='SERVICO',
        ),
    ]
